<?php

namespace Test\AJT\Toggl;

use AJT\Toggl\ReportsClient;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-10-10 at 13:34:22.
 */
class ReportsClientTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var ReportsClient
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new ReportsClient(['api_key' => constant('TOGGLE_TOKEN'), 'debug' => true]);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AJT\Toggl\ReportsClient::factory
     * @todo   Implement testfactory().
     */
    public function testfactory() {
        $this->assertEquals('', \AJT\Toggl\TogglClient::factory(['api_key' => constant('TOGGLE_TOKEN'), 'debug' => true]));
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AJT\Toggl\ReportsClient::__call
     * @todo   Implement test__call().
     */
    public function test__call() {
        $this->assertEquals('', $this->object->__call());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

}
