<?php

namespace Test\AJT\Toggl;

use AJT\Toggl\TogglClient;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-10-10 at 13:35:13.
 */
class TogglClientTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var TogglClient
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = \AJT\Toggl\TogglClient::factory(['api_key' => constant('TOGGLE_TOKEN'), 'debug' => true]);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AJT\Toggl\TogglClient::factory
     */
    public function testfactory() {
        $this->assertInstanceOf('GuzzleHttp\Command\Guzzle\GuzzleClient', \AJT\Toggl\TogglClient::factory(['api_key' => constant('TOGGLE_TOKEN')]));
    }

    /**
     * @covers AJT\Toggl\TogglClient::__call
     * @todo   Implement test__call().
     */
    public function test__call() {
        $this->assertEquals('', $this->object->__call());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

}
